image: gitpod/workspace-full

tasks:
  - name: Setup Bun
    command: curl -fsSL https://bun.sh/install | bash

  - name: Setup Project
    command: bun install

  - name: Run Server
    command: bun --bun dev -- --open
